export const FILTER_BY_AUTHOR = "FILTER/FILTER_BY_AUTHOR";
export const FILTER_BY_TITLE = "FILTER/FILTER_BY_TITLE";
export const FILTER_BY_CATEGORY = "FILTER/FILTER_BY_CATEGORY";
export const RESET_BY_AUTHOR = "FILTER/RESET_BY_AUTHOR";
export const RESET_BY_TITLE = "FILTER/RESET_BY_TITLE";
export const RESET_BY_CATEGORY = "FILTER/RESET_BY_CATEGORY";
export const RESET_ALL = "FILTER/RESET_ALL";
