export const initialState = [
    {
        id: 1,
        title: "Occupant of anml-drn vehicle injured in collisn with same",
        category: "EIFS",
        author: "Mash",
        createdAt: "6/2/2022",
        read: 4,
        image: "https://images.pexels.com/photos/956981/milky-way-starry-sky-night-sky-star-956981.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },
    {
        id: 2,
        title: "Corrosion of third degree of left forearm, initial encounter",
        category: "Control",
        author: "Don",
        createdAt: "2/7/2022",
        read: 1,
        image: "https://images.pexels.com/photos/1983032/pexels-photo-1983032.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
        id: 3,
        title: "Occup of bus injured in collision w hv veh in traf",
        category: "Termite",
        author: "Mash",
        createdAt: "11/4/2022",
        read: 2,
        image: "https://images.pexels.com/photos/167843/milky-way-rocks-night-landscape-167843.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
        id: 4,
        title: "Contact with sword or dagger, initial encounter",
        category: "EIFS",
        author: "Gerianne Creer",
        createdAt: "10/4/2022",
        read: 5,
        image: "https://images.pexels.com/photos/39561/solar-flare-sun-eruption-energy-39561.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
        id: 5,
        title: "Contusion of left little finger with damage to nail, sequela",
        category: "Construction",
        author: "Sakib",
        createdAt: "10/11/2021",
        read: 1,
        image: "https://images.pexels.com/photos/33688/delicate-arch-night-stars-landscape.jpg?auto=compress&cs=tinysrgb&w=600",
    },
    {
        id: 6,
        title: "Toxic effect of gases, fumes and vapors, assault, sequela",
        category: "Termite",
        author: "Alvie ",
        createdAt: "30/6/2022",
        read: 7,
        image: "https://images.pexels.com/photos/1169754/pexels-photo-1169754.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
        id: 7,
        title: "Encounter for screening for osteoporosis",
        category: "Construction",
        author: "Tanhya Purdy",
        createdAt: "15/8/2022",
        read: 3,
        image: "https://images.pexels.com/photos/2078126/pexels-photo-2078126.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
        id: 8,
        title: "Garage of reform school as place",
        category: "Fencing",
        author: "Ebbens",
        createdAt: "27/4/2022",
        read: 9,
        image: "https://images.pexels.com/photos/2150/sky-space-dark-galaxy.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },
    {
        id: 9,
        title: "Perinatal hematological disorder, unspecified",
        category: "Fencing",
        author: "Alvie",
        createdAt: "23/6/2022",
        read: 10,
        image: "https://images.pexels.com/photos/956999/milky-way-starry-sky-night-sky-star-956999.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1f",
    },
];
